### ISSUE TITLE
Error trying to read form-data of signed document: 444 "The custom error module does not recognize this error"

### ISSUE THREAD

**Issue by epicguy** [docusign/docusign-esign-node-client#295] opened 2022-06-16 19:02 UTC
For the first time, starting about 8:30 am MDT today (Jun 16), using NodeJS package, trying to retrieve form-data from a signed document, I get error: 'The custom error module does not recognize this error.' and status: 444, and message: 'Unsuccessful HTTP response'. See detail below. I opened a ticket with DocuSign support, but I'm not getting any responses.

This is the basically the code I am using. Seems the error is thrown on that last line
```
const accessToken = await this._getAccessToken(ctx) // Refreshes each hour
let dsApiClient = new docusignESign.ApiClient()
dsApiClient.setBasePath(this.config.baseAccountUri)
dsApiClient.addDefaultHeader('Authorization', 'Bearer ' + accessToken)
let envelopesApi = new docusignESign.EnvelopesApi(dsApiClient)
let results = await envelopesApi.getFormData(this.config.baseAccountId, envelopeId)
```

The following is the error that comes back
```
{
"name": "Error",
"stack": "Error: Unsuccessful HTTP response\n    at Request.callback (/app/node_modules/superagent/lib/node/index.js:696:15)\n    at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/index.js:906:18)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
"status": 444,
"message": "Unsuccessful HTTP response",
"response": {
"req": {
"url": "https://demo.docusign.net/restapi/v2.1/accounts/723b4584-e964-4391-bb2d-42e6050e477e/envelopes/582420aa-6808-46e0-806c-0fd9aec4f786/form_data",
"data": { },
"method": "GET",
"headers": {
"accept": "application/json",
"node-ver": "v16.15.1",
"user-agent": "node-superagent/3.8.2",
"content-type": "application/json",
"authorization": "Bearer eyJ0eXAiOiJNVCIs...OAgg",
"x-docusign-sdk": "Node"
}
},
"text": "The custom error module does not recognize this error.",
"header": {
"date": "Thu, 16 Jun 2022 16:57:22 GMT",
"connection": "close",
"content-type": "text/html",
"content-length": "54",
"x-docusign-node": "DA1DFE4",
"x-docusign-tracetoken": "c5aab93d-1644-4f84-b745-e5344b11c767",
"strict-transport-security": "max-age=31536000; includeSubDomains"
},
"status": 444
}
```

Case info... 
```
Case #: 09640094 
Account #: 13339722-na4 
Subject: Unexpected errors occuring when retrieving form-data from a signed envelope 
```

**Comment by epicguy** [comment] 2022-06-16 19:06
Just FYI, this is on the sandbox (demo) but the same code is still working in production. Also, it seems someone on stackoverflow is seeing the same issue, also using nodejs sdk ... https://stackoverflow.com/questions/72647783/docusign-api-error-in-fetching-documentbase64-through-docusign-node-js-sdk

**Comment by Kushagra8888** [comment] 2022-06-16 19:13
Apparently this error is related to IIS which is what must be used by docusign and might be a result of some configuration changes. I suppose this might also happen for other GET calls happening through the SDK. I was able to reproduce the same through Postman by passing an empty object in the body field for a GET request (which is what the SDK also does).
![image](https://user-images.githubusercontent.com/5831228/174147370-7ef142a6-6302-4aff-aebd-ae37b746b240.png)

**Comment by epicguy** [comment] 2022-06-16 21:46
@Kushagra8888 I have confirmed that if the sdk calls send with an empty string body, the error does not occur. I'm going to be curious if this patch could also work without incident in production, so I can use the one codebase while this issue is in play.

```
diff --git a/src/ApiClient.js b/src/ApiClient.js
index 6fe838f..6fc1050 100644
--- a/src/ApiClient.js
+++ b/src/ApiClient.js
@@ -552,7 +552,7 @@
         }
       }
     } else if (body) {
-      request.send(removeNulls(body));
+      request.send( bodyParam=== false ? '': removeNulls(body));
     }
 
     var accept = this.jsonPreferredMime(accepts);
diff --git a/src/api/EnvelopesApi.js b/src/api/EnvelopesApi.js
index b07c1e0..30c126b 100644
--- a/src/api/EnvelopesApi.js
+++ b/src/api/EnvelopesApi.js
@@ -4174,7 +4174,7 @@ To retrieve the combined content replace the `{documentId}` parameter in the end
      * data is of type: {@link module:model/EnvelopeFormData}
      */
     this.getFormData = function(accountId, envelopeId, callback) {
-      var postBody = null;
+      var postBody = false; // JCS: false means to send no body at all
 
       // verify the required parameter 'accountId' is set
       if (accountId === undefined || accountId === null) {
```

**Comment by MichaelBuhler** [comment] 2022-06-17 07:42
+1

My organization is also experiencing this novel issue in the last 1-2 days.

**Comment by MichaelBuhler** [comment] 2022-06-17 07:46
Empty body works:

<img width="650" alt="Screen Shot 2022-06-17 at 2 44 11 PM" src="https://user-images.githubusercontent.com/9561039/174251367-e221bc77-9100-47b4-aae6-109371ebdc74.png">

`{}` body fails:

<img width="690" alt="Screen Shot 2022-06-17 at 2 44 01 PM" src="https://user-images.githubusercontent.com/9561039/174251411-db9a21eb-1374-4838-96a9-b9e8ee453546.png">

**Comment by brunomilicevic-croatia** [comment] 2022-06-17 10:59
We are having the same issue, but with downloading of documents.

We lowered sdk version to 5.7 since in 5.8 the empty body change was introduced.

**Comment by dkabx** [comment] 2022-06-17 13:06
facing the same issue while fetching documentbase64 through DocuSign node js

**Comment by epicguy** [comment] 2022-06-17 13:51
Thanks @brunomilicevic-croatia.  @dbbrahmbhatt Can you comment on this line in ApiClient.js? (If I'm reading "git" correctly it looks like it could be from your pull request.) I only use the NodeJS SDK, so I'm limited in my API knowledge. Also, as @Kushagra8888 says, this may only be a misconfigured IIS server issue in the demo servers...

```
var body = bodyParam || {};
```

```
commit c4dfdaa31eb0e81e15308c03321d80f2556241cd (tag: v5.8.1)
Author: Dhaval Brahmbhatt <32913565+dbbrahmbhatt@users.noreply.github.com>
Date:   Fri Oct 30 15:27:12 2020 -0700

    Version 5.8.1-v2.1-20.3.01 release (#229)
    
    Co-authored-by: DevCenter-DocuSign <dcdev@docusign.com>

```

**Comment by Garren** [comment] 2022-06-17 14:43
Also seeing the issue. [Docusign, Node SDK, JWT auth, Envelope fetch, "The custom error module does not recognize this error."](https://stackoverflow.com/questions/72653581/docusign-node-sdk-jwt-auth-envelope-fetch-the-custom-error-module-does-not)

In a nutshell, I captured the SDK request through a proxy, then copied as curl command. The SDK request fails with the "The custom error module..." error. The curl command, copied from the proxy's logged request (same as Chrome or Firefox) succeeds though, and I have no idea why that would be the case.

I also noticed the empty body that the sdk was including, but the copied curl request succeeds with or without it - although *with* the body I only get a single result back when querying for multiple envelopes. 

```shell
[MacBookPro0020]~:0
$ curl 'https://demo.docusign.net/restapi/v2.1/accounts/a0a4c81f-3cd0-4737-880c-f40e74206d1b/envelopes?envelope_ids=e750526f-0fd9-4342-b4fd-8232e6e2dd68&envelope_ids=a38b794b-c1e4-4433-8ac2-e98260f82c6e&envelope_ids=a5d8c586-259d-48b0-aa78-49f422113be2&envelope_ids=e1917111-2900-48e8-9054-799169379c8a&envelope_ids=a82328dd-5fbe-44b4-9127-375afaf00323&envelope_ids=f4de37f8-c000-46c8-aebc-76b82f92f2c3&envelope_ids=5a430e35-39d2-4b44-bc72-2ca541873d20&envelope_ids=f445b0a7-8413-4917-820d-9276d9892e62&envelope_ids=d97565c8-8116-4f2c-90e5-8d8d118688af' \
-H 'Host: demo.docusign.net' \
-H 'User-Agent: node-superagent/3.8.2' \
-H 'X-DocuSign-SDK: Node' \
-H 'Node-Ver: v14.18.3' \
-H 'Authorization: Bearer ABCD...' \
-H 'Accept: application/json' \
-H 'Content-Length: 2' \
-H 'Connection: close' \
-H 'Content-Type: application/json' \
-d '{}' \
--proxy http://localhost:9090
{"envelopeId":"eef3593e-9d7b-42fa-bc77-0f8a76babe40","uri":"/envelopes/eef3593e-9d7b-42fa-bc77-0f8a76babe40","statusDateTime":"2022-06-17T14:36:20.5770000Z","status":"created"}%
```
Without the body I get a collection back.
```shell
[MacBookPro0020]~:0
$ curl 'https://demo.docusign.net/restapi/v2.1/accounts/a0a4c81f-3cd0-4737-880c-f40e74206d1b/envelopes?envelope_ids=e750526f-0fd9-4342-b4fd-8232e6e2dd68&envelope_ids=a38b794b-c1e4-4433-8ac2-e98260f82c6e&envelope_ids=a5d8c586-259d-48b0-aa78-49f422113be2&envelope_ids=e1917111-2900-48e8-9054-799169379c8a&envelope_ids=a82328dd-5fbe-44b4-9127-375afaf00323&envelope_ids=f4de37f8-c000-46c8-aebc-76b82f92f2c3&envelope_ids=5a430e35-39d2-4b44-bc72-2ca541873d20&envelope_ids=f445b0a7-8413-4917-820d-9276d9892e62&envelope_ids=d97565c8-8116-4f2c-90e5-8d8d118688af' \
-H 'Host: demo.docusign.net' \
-H 'User-Agent: node-superagent/3.8.2' \
-H 'X-DocuSign-SDK: Node' \
-H 'Node-Ver: v14.18.3' \
-H 'Authorization: Bearer ABCD...' \
-H 'Accept: application/json' \
-H 'Connection: close' \
-H 'Content-Type: application/json' \
--proxy http://localhost:9090
{"resultSetSize":"1","startPosition":"0","endPosition":"0","totalSetSize":"1","nextUri":"","previousUri":"","envelopes":[{"status":"created","documentsUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/documents","recipientsUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/recipients","attachmentsUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/attachments","envelopeUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af","emailSubject":"Please sign this document set.","emailBlurb":"Sample text for email body.","envelopeId":"d97565c8-8116-4f2c-90e5-8d8d118688af","signingLocation":"online","customFieldsUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/custom_fields","notificationUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/notification","enableWetSign":"true","allowMarkup":"false","allowReassign":"true","createdDateTime":"2022-05-24T16:23:34.2700000Z","lastModifiedDateTime":"2022-05-24T16:23:34.2700000Z","statusChangedDateTime":"2022-05-24T16:23:34.2700000Z","documentsCombinedUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/documents/combined","certificateUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/documents/certificate","templatesUri":"/envelopes/d97565c8-8116-4f2c-90e5-8d8d118688af/templates","sender":{"userName":"Adam Garren","userId":"1dd08c0d-fedb-481a-8a4c-8347bbfc6e8e","accountId":"a0a4c81f-3cd0-4737-880c-f40e74206d1b","email":"me@test.com"},"purgeState":"unpurged","envelopeIdStamping":"true","autoNavigation":"true","isSignatureProviderEnvelope":"false","allowComments":"true","anySigner":null,"envelopeLocation":"current_site"}]}%

```

**Comment by Kushagra8888** [comment] 2022-06-17 14:52
@Garren I think the curl with `-d` is turning it into a POST request, you can see that it returns a new envelope id.

**Comment by Garren** [comment] 2022-06-17 15:23
@Kushagra8888, I missed that, you're right. I overlooked the status in the post. Thanks!

**Comment by JeuneApprenti** [comment] 2022-06-17 15:24
@brunomilicevic-croatia Your solution works as a workaround for me too.

**Comment by epicguy** [comment] 2022-06-17 17:59
I thought support might update this issue - here is the response I got in my ticket a few hours ago ...
```
Steve Docusign, Inc.
06/17/2022
	
Hello,

Thank you for clarifying this and creating the Github issue for better visibility. This issue appears to be related to some recent security rule enhancements that were implemented on our API. Please be assured that we are actively investigating a solution to this issue and will release a fix as soon as possible. I will provide you with updates on this case as the investigation progresses.

Please let me know if you have any questions in the meantime.

Best regards,

Steve | DocuSign Developer Support
```

**Comment by InbarGazit** [comment] 2022-06-17 19:20
Thanks for your patience everyone. We are aware and working on this. Hope to have an update soon.

**Comment by InbarGazit** [comment] 2022-06-17 20:05
This should be resolved now. Can someone confirm?

**Comment by epicguy** [comment] 2022-06-17 20:43
@InbarGazit Yes, this is working just as it was before, thanks!

**Comment by Garren** [comment] 2022-06-17 20:51
@InbarGazit Still testing but it appears to be working

**Comment by InbarGazit** [comment] 2022-06-17 20:59
Thanks, I'm closing this.

**Closed by InbarGazit** 2022-06-17 20:59 UTC

**Comment by dgerbe** [comment] 2022-08-23 16:22
@InbarGazit I'm seeing a similar issue with sandbox (demo) today. Has this issue been reintroduced?

**Comment by epicguy** [comment] 2022-08-23 16:54
@dgerbe My original issue is not a problem as of a few mins ago, just checked.
