### ISSUE TITLE
`EnvelopesApi.getDocument()` returns the document string with 'undefined' prepended

### ISSUE THREAD

**Issue by ebarr006** [docusign/docusign-esign-node-client#354] opened 2024-05-31 20:26 UTC
After upgrading to v7.0.1, we saw that our document strings have `undefined` prepended.

![undefined-prepended](https://github.com/docusign/docusign-esign-node-client/assets/10412150/510beb68-8f97-4301-93c1-05b4c1fdf16b)

We were upgrading from 6.3.0

**Comment by DocuSignEric** [comment] 2024-06-01 16:37
Hello @ebarr006 

Thank you very much for sharing this information, is it possible that you can attach the logs when you perform this action?

https://support.docusign.com/guides/ndse-user-guide-api-request-logging

Regards,

Eric | Docusign

**Comment by garg-mudit** [comment] 2024-06-03 09:52
Hi @ebarr006,
I am a part of Developer Experience team within Docusign and currently looking into this issue. We have identified the problem on our end and will be pushing a patch soon for the same.

Thank You.

**Comment by mmccarl** [comment] 2024-06-04 20:08
in addition to the 'undefined' prefix, i also noticed that bytes with the high order bit seem to all be "\xfd" values.  here's a dump of the first several bytes of the getDocument response as well as the first part of the same document that was downloaded via the web interface:

00000000  75 6e 64 65 66 69 6e 65  64 25 50 44 46 2d 31 2e  |undefined%PDF-1.|
00000010  37 0a 25 **fd fd fd fd** 0a  39 20 30 20 6f 62 6a 0a  |7.%.....9 0 obj.|
00000020  3c 3c 2f 4c 65 6e 67 74  68 20 34 3e 3e 73 74 72  |<</Length 4>>str|
00000030  65 61 6d 0a 0a 20 71 20  0a 65 6e 64 73 74 72 65  |eam.. q .endstre|

from the web interface:

00000000: 25 50 44 46 2d 31 2e 37 0a 25 **fb fc fd fe** 0a 39  :%PDF-1.7.%.....9:
00000010: 20 30 20 6f 62 6a 0a 3c 3c 2f 4c 65 6e 67 74 68  : 0 obj.<</Length:
00000020: 20 34 3e 3e 73 74 72 65 61 6d 0a 0a 20 71 20 0a  : 4>>stream.. q .:
00000030: 65 6e 64 73 74 72 65 61 6d 0a 65 6e 64 6f 62 6a  :endstream.endobj:

note that the 'fd fd fd fd' in the first dump at offset 103 should be 'fb fc fd fe' as shown in the second dump at offset 0a.  this happens to all bytes with the high order bit set.

**Comment by gsf4726** [comment] 2024-06-05 12:21
@garg-mudit Any updates on the fix for this? We just recently ran into this issue after upgrading to v7.0.1. It's a critical issue for us.

**Comment by garg-mudit** [comment] 2024-06-05 16:24
Hi @gsf4726 ,
The fix has been made internally and will hopefully be released by the end of  this week.

Thank You.

**Comment by garg-mudit** [comment] 2024-06-06 11:10
Hi @ebarr006, @mmccarl, @gsf4726 ,

A new patch version 7.0.2 was released for fixing the issue. Please try it out. In case the issue still persists, then please feel free to mention the same here and I will try my best to get the same resolved by EOW.

**Comment by mmccarl** [comment] 2024-06-06 12:08
much better!  i now get a valid pdf.

i noticed that when i request a specific document id, the size of the file i get is a few bytes larger than when i request 'combined'.  there are a bunch of differences in the files, but still i get only one pdf file when requesting 'combined' whereas the web interface gives a zip file when 'all' is selected.

could you give me a description of the differences between the web results and using 'combined' and also the differences between 'combined' vs a specific documentId?  (note: the envelope i'm testing with has only one document).

**Comment by garg-mudit** [comment] 2024-06-06 19:43
Hi @mmccarl ,

> i noticed that when i request a specific document id, the size of the file i get is a few bytes larger than when i request 'combined'.

I might need to look into this part. I will get back to you on this once I have more info.

> there are a bunch of differences in the files, but still i get only one pdf file when requesting 'combined' whereas the web interface gives a zip file when 'all' is selected.

In short, we can use different values of `documentId` while request a document to fetch different format among other things.

Please have a look at [this](https://developers.docusign.com/docs/esign-rest-api/how-to/download-envelope-documents/) blog to get more idea on this.

![image](https://github.com/docusign/docusign-esign-node-client/assets/35302867/641311e5-9b52-4f64-8f51-88cbeac28693)

Hope that answers your question. Please let us know if you have any other doubts/issues while integrating with Docusign. We are happy to help.

Thank You.

**Comment by mmccarl** [comment] 2024-06-06 20:00
thank you.  i think the blog post describes what i want to do.

it would be nice if the [reference page](https://docusign.github.io/docusign-esign-node-client/) had more information such as allowed values for parameters (in the models) and usage rules (for the methods).

**Comment by garg-mudit** [comment] 2024-06-10 08:12
Hi @mmccarl,
Thank you for suggesting the reference pages enhancement. I'll pass your feedback to the eSign Core API team to enhance the description.

Since the issue is resolved on your end, I will close the ticket. If the problem persists, please feel free to reopen the ticket or create a new one. We're always here to help.

Thank You.

**Closed by garg-mudit** 2024-06-10 08:12 UTC
Labels: responded
